language: ruby
rvm:
  - 2.3.3


addons:
  firefox: latest
before_script:
  - cp  config/database.yml config/database.travis.yml
  - psql -c 'create database flashcards_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
