language: ruby
rvm:
  - 2.3.3
addons:
  firefox: latest
  cache: bundler
before_script:
  - sudo service postgresql stop
  - sudo service postgresql start
  # - psql -c 'create database flashcards1_test;' -U postgres
  - bundle exec rake db:setup
  - bin/rake db:migrate RAILS_ENV=test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
